ALTER TABLE line_item_pickup MODIFY COLUMN flight_number varchar(200);
ALTER TABLE line_item_pickup MODIFY COLUMN pickup_to_postalcode varchar(200);



update city set name_ch = '阿伯丁' where id =1;
update city set name_ch = '阿伯里斯特维斯' where id =2;
update city set name_ch = '班戈' where id =3;
update city set name_ch = '巴斯' where id =4;
update city set name_ch = '贝尔法斯特' where id =5;
update city set name_ch = '伯明翰' where id =6;
update city set name_ch = '博尔顿' where id =7;
update city set name_ch = '伯恩茅斯' where id =8;
update city set name_ch = '布拉德福德' where id =9;
update city set name_ch = '布里德灵顿' where id =10;
update city set name_ch = '布莱顿' where id =11;
update city set name_ch = '布里斯托' where id =12;
update city set name_ch = '白金汉' where id =13;
update city set name_ch = '剑桥' where id =14;
update city set name_ch = '坎特伯里' where id =15;
update city set name_ch = '卡迪夫' where id =16;
update city set name_ch = '切尔滕纳姆' where id =17;
update city set name_ch = '切斯特' where id =18;
update city set name_ch = '奇切斯特' where id =19;
update city set name_ch = '科尔切斯特' where id =20;
update city set name_ch = '考文垂' where id =21;
update city set name_ch = '德比' where id =22;
update city set name_ch = '邓迪' where id =23;
update city set name_ch = '杜伦' where id =24;
update city set name_ch = '爱丁堡' where id =25;
update city set name_ch = '埃克赛特' where id =26;
update city set name_ch = '法尔茅斯' where id =27;
update city set name_ch = '吉灵厄姆' where id =28;
update city set name_ch = '格拉斯哥' where id =29;
update city set name_ch = '赫特福德' where id =30;
update city set name_ch = '哈德斯菲尔德' where id =31;
update city set name_ch = '赫尔' where id =32;
update city set name_ch = '因弗内斯' where id =33;
update city set name_ch = '基尔' where id =34;
update city set name_ch = '肯特' where id =35;
update city set name_ch = '金斯顿' where id =36;
update city set name_ch = '兰卡斯特' where id =37;
update city set name_ch = '利兹' where id =38;
update city set name_ch = '莱斯特' where id =39;
update city set name_ch = '林肯' where id =40;
update city set name_ch = '利物浦' where id =41;
update city set name_ch = '伦敦' where id =42;
update city set name_ch = '拉夫堡' where id =43;
update city set name_ch = '卢顿' where id =44;
update city set name_ch = '曼彻斯特' where id =45;
update city set name_ch = '米德尔斯堡' where id =46;
update city set name_ch = '米德尔塞克斯 ' where id =47;
update city set name_ch = '纽卡斯尔' where id =48;
update city set name_ch = '北安普顿' where id =49;
update city set name_ch = '诺威治' where id =50;
update city set name_ch = '诺丁汉' where id =51;
update city set name_ch = '牛津' where id =52;
update city set name_ch = '奥克斯特德' where id =53;
update city set name_ch = '佩斯利' where id =54;
update city set name_ch = '普利茅斯' where id =55;
update city set name_ch = '朴茨茅斯' where id =56;
update city set name_ch = '普雷斯顿' where id =57;
update city set name_ch = '雷丁' where id =58;
update city set name_ch = '索尔福德' where id =59;
update city set name_ch = '谢菲尔德' where id =60;
update city set name_ch = '南安普顿' where id =61;
update city set name_ch = '圣安德鲁斯' where id =62;
update city set name_ch = '史塔福' where id =63;
update city set name_ch = '斯特灵' where id =64;
update city set name_ch = '斯托克' where id =65;
update city set name_ch = '桑德兰' where id =66;
update city set name_ch = '萨里' where id =67;
update city set name_ch = '斯旺西' where id =68;
update city set name_ch = '温切斯特' where id =69;
update city set name_ch = '伍尔夫汉普顿' where id =70;
update city set name_ch = '伍斯特' where id =71;
update city set name_ch = '雷克瑟姆' where id =72;
update city set name_ch = '约克' where id =73;
update city set name_ch = '科尔雷恩' where id =74;
update city set name_ch = '纽敦阿比' where id =75;
update city set name_ch = '伦敦德里' where id =76;
update city set name_ch = '斯特拉特福德' where id =77;
update city set name_ch = '伊斯特本' where id =78;
update city set name_ch = '黑斯廷斯' where id =79;
update city set name_ch = '格洛斯特' where id =80;
update city set name_ch = '海威科姆' where id =81;
update city set name_ch = '阿克斯布里奇' where id =82;
update city set name_ch = '切姆斯福德' where id =83;
update city set name_ch = '彼得伯勒' where id =84;
update city set name_ch = '布罗德斯泰斯' where id =85;
update city set name_ch = '查塔姆' where id =86;
update city set name_ch = '坦布里奇威尔斯' where id =87;
update city set name_ch = '埃普索姆' where id =88;
update city set name_ch = '法纳姆' where id =89;
update city set name_ch = '梅德斯通' where id =90;
update city set name_ch = '罗切斯特' where id =91;
update city set name_ch = '沃灵顿' where id =92;
update city set name_ch = '博格诺里吉斯' where id =93;
update city set name_ch = '劳顿' where id =94;
update city set name_ch = '滨海绍森德' where id =95;
update city set name_ch = '巴克斯顿' where id =96;
update city set name_ch = '切斯特菲尔德' where id =97;
update city set name_ch = '蒂斯河畔斯托克顿' where id =98;
update city set name_ch = '塞尔克内斯' where id =99;
update city set name_ch = '斯特罗姆内斯' where id =100;
update city set name_ch = '彭林' where id =101;
update city set name_ch = '特鲁罗' where id =102;
update city set name_ch = '邓弗里斯' where id =103;
update city set name_ch = '哈特菲尔德' where id =104;
update city set name_ch = '斯卡伯勒' where id =105;
update city set name_ch = '汤布里奇' where id =106;
update city set name_ch = '巴罗弗内斯' where id =107;
update city set name_ch = '艾格汉' where id =108;
update city set name_ch = '哈罗' where id =109;
update city set name_ch = '布伦特福德' where id =110;
update city set name_ch = '阿斯科特' where id =111;
update city set name_ch = '贝德福德' where id =112;
update city set name_ch = '米尔顿凯恩斯' where id =113;
update city set name_ch = '达灵顿' where id =114;
update city set name_ch = '索思韦尔' where id =115;
update city set name_ch = '兰开夏郡' where id =116;
update city set name_ch = '汉密尔顿' where id =117;
update city set name_ch = '坎布里亚' where id =118;
update city set name_ch = '利奇菲尔德' where id =119;
update city set name_ch = '什鲁斯伯里' where id =120;
update city set name_ch = '斯托诺韦' where id =121;
update city set name_ch = '弗林特郡' where id =122;
update city set name_ch = '纽波特' where id =123;
update city set name_ch = '梅德韦' where id =124;

update city set topCity = 'false';
update city set topCity = 'true' where id in (42, 6, 38, 41, 16, 31, 9, 12, 57, 45, 29, 25, 48, 51, 60);

update college set topCollege = 'false';
update college set topCollege = 'true' where id in (89, 130, 183, 184, 189, 197, 229, 270);
commit;