insert into contract_type (id, name, create_time, update_time) values (1, '详询客服', now(), now());
insert into contract_type (id, name, create_time, update_time) values (2, '39周零6天', now(), now());
insert into contract_type (id, name, create_time, update_time) values (3, '40周', now(), now());
insert into contract_type (id, name, create_time, update_time) values (4, '40周零1天', now(), now());
insert into contract_type (id, name, create_time, update_time) values (5, '40周零2天', now(), now());
insert into contract_type (id, name, create_time, update_time) values (6, '41周', now(), now());
insert into contract_type (id, name, create_time, update_time) values (7, '41周零2天', now(), now());
insert into contract_type (id, name, create_time, update_time) values (8, '42周', now(), now());
insert into contract_type (id, name, create_time, update_time) values (9, '42周以上', now(), now());
