source F:\GitHub\Dormitory\sql\contract_type_init.sql
source F:\GitHub\Dormitory\sql\dormitory_init.sql
source F:\GitHub\Dormitory\sql\dormitory_type_init.sql
source F:\GitHub\Dormitory\sql\user_init.sql
source F:\GitHub\Dormitory\sql\order_init.sql
source F:\GitHub\Dormitory\sql\order_contact_info_init.sql
source F:\GitHub\Dormitory\sql\line_item_dormitory_init.sql
source F:\GitHub\Dormitory\sql\line_item_pickup_init.sql
source F:\GitHub\Dormitory\sql\order_history_init.sql
